"""
Agent Orchestrator.

Coordinates agent execution flow.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import replace
from typing import Any

from agentplatform.application.execution import AgentExecutionService
from agentplatform.domain.context import AgentExecutionContext
from agentplatform.domain.contracts import AgentContract
from agentplatform.domain.results import AgentResult
from agentplatform.domain.review import ReviewResult


class AgentOrchestrator:
    """
    Coordinates multiple agents in an execution pipeline.

    Each agent receives the accumulated context
    generated by previous agents.
    """

    def __init__(
        self,
        execution_service: AgentExecutionService,
        max_iterations: int = 3,
    ) -> None:
        self._execution_service = execution_service
        self._max_iterations = max_iterations

    def execute_pipeline(
        self,
        agents: Sequence[AgentContract],
        context: AgentExecutionContext,
    ) -> list[AgentResult]:
        """
        Execute ordered agent pipeline.
        """
        print("========== ENTERED ORCHESTRATOR ==========")

        results: list[AgentResult] = []

        current_context = context

        print("Context = ", context)
        print("maxitter = ", self._max_iterations)

        for _ in range(self._max_iterations):

            iteration_results: list[AgentResult] = []

            for agent in agents:

                print(
                    "RUNNING AGENT:",
                    agent.name,
                )

                print(
                    "BEFORE CONTEXT KEYS:",
                    current_context.metadata.keys(),
                )

                result = self._execution_service.execute(
                    agent,
                    current_context,
                )

                iteration_results.append(
                    result,
                )

                if result.success:
                    current_context = self._merge_result_context(
                        current_context,
                        result,
                    )

                    print(
                        "AFTER CONTEXT KEYS:",
                        current_context.metadata.keys(),
                    )

                    print(
                        "HAS ARCH PLAN:",
                        "architecture_plan" in current_context.metadata,
                    )

                print(
                    "HANDOFF TO NEXT AGENT:",
                    current_context.metadata.get(
                        "architecture_plan",
                    ),
                )

                if (
                    agent.name == "architect"
                    and "architecture_plan" not in current_context.metadata
                ):
                    raise RuntimeError(
                        "Architect result missing architecture_plan propagation.",
                    )

                print(
                    "DEBUG RESULT:",
                    agent.name,
                    result.data.keys(),
                )

                print(
                    "DEBUG CONTEXT:",
                    current_context.metadata.keys(),
                )

            results.extend(
                iteration_results,
            )

            if not self._needs_retry(
                iteration_results,
            ):
                break

        return results

    def _merge_result_context(
        self,
        context: AgentExecutionContext,
        result: AgentResult,
    ) -> AgentExecutionContext:
        """
        Transfer agent output into next agent context.
        """

        metadata = dict(context.metadata)

        metadata["agent_results"] = {
            **metadata.get(
                "agent_results",
                {},
            ),
            result.data.get(
                "agent",
                "unknown",
            ): result.data,
        }

        if "architecture_plan" in result.data:
            metadata["architecture_plan"] = result.data["architecture_plan"]

        return replace(
            context,
            metadata=metadata,
        )

    def _needs_retry(
        self,
        results: Sequence[AgentResult],
    ) -> bool:
        """
        Determine whether another iteration is needed.
        """

        for result in results:

            review: Any = result.data.get(
                "review",
            )

            if isinstance(
                review,
                ReviewResult,
            ):
                return not review.approved

        return False
